-- Create users table [RIGHT CLICK ON TABLES AND CLICK ‘EXECUTE COMMAND’]:
CREATE TABLE USERS (EMAIL VARCHAR(50) NOT NULL, "NAME" VARCHAR(50), PASSWORD VARCHAR(20), GENDER VARCHAR(20), ADDRESS VARCHAR(50), PRIMARY KEY (EMAIL));
